<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypeid="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>rosidl_generator_connext_cpp</name>
  <version>0.1.0</version>
  <description>Generate RTI Connext DDS C++ typesupport from ROS interface definitions</description>
  <maintainer email="your.email@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <build_depend>rosidl_generator_c</build_depend>
  <build_depend>rosidl_generator_cpp</build_depend>
  <build_depend>rosidl_typesupport_interface</build_depend>

  <exec_depend>rosidl_generator_c</exec_depend>
  <exec_depend>rosidl_generator_cpp</exec_depend>
  <exec_depend>rosidl_typesupport_interface</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <member_of_group>rosidl_generator_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>